### ISSUE TITLE
Lockview is causing console Hooks to be spammed 20x per seconds, this gets worse with the more Gms and more players connection

### ISSUE THREAD

**Issue by Zarhog** [CDeenen/LockView#101]
![image](https://github.com/CDeenen/LockView/assets/76391362/7dc1b19a-b442-48c0-b5e7-23cb8b8554e7)

**Comment by p4535992** [comment]
same issue

**Comment by Zarhog** [comment]
so we found this this is because the modual is only written with 1 GM in mind. and dose not account for Gms using VPNS or international Gms 

The mod auther has said he would like to re-write and fit it but cannot find the time,


im curiouse what is the time required and what is the cost of sed time? this this something you would be open to other mod cretors fixing? and workiong with them on?

**Comment by CDeenen** [comment]
The console spam issue is actually just a debug line that I forgot to comment out (line 13 in src/socket.js). However, it should not happen constantly, but the multiple DM issue might cause that.

Time is indeed a big problem for me atm, which is why this, and several other issues have not been addressed yet.

Regarding fixing the multiple DM issue, I'm not sure how much time that'd require, but I am open to other devs fixing things.

**Comment by Zarhog** [comment]
This is good to hear, if you dont manage to find a solution in about 3-4 months i may look to see if i can find somone willing to help fix the problem :), as i love this modual and see it as nesicery for Foundry VTT to be a more profesional looking software

**Comment by Zarhog** [comment]
Any updates?

**Comment by CDeenen** [comment]
This specific issue (console spam) has been fixed in the last update, which is why I'm closing this issue.
You're probably asking about the multiple GM issue (which is issue #97), though , for which there is no update yet.
