### ISSUE TITLE
Way to move only one Viewport at a time

### ISSUE THREAD

**Issue by Brimcon** [CDeenen/LockView#24]
For more cinematic or stream games. There should be a way to move only one particular Viewbox, but not others. Even with Viewbox disabled on multiple players, Edit Viewbox will move all viewboxes.

**Comment by CDeenen** [comment]
Thank you for your suggestion. Moving the view when Viewbox is disabled for players isn't supposed to happen. I'll get that fixed.
Being able to move only one viewbox at a time would be a great addition. Ideally each viewbox would have 2 small icons, perhaps one in the top-left of the box and one in the lower-right. Dragging one of these icons would then drag the viewbox (and the player's view) around, while the other one would change the size of the viewbox.
I've got a big update planned for in a few days that should greatly improve stability and performance and fix some bugs. If I can find the time I'll try to add this, otherwise it'll have to wait until a later update.

**Comment by CDeenen** [comment]
I've added it to the 1.4.1 beta version that you can try if you like.
Manifest url: https://github.com/CDeenen/LockView/releases/download/v1.4.1/module.json

Since I've rewritten much of the code, and I haven't had a lot of time to test it, I cannot promise trouble-free operation. But feel free to give it a go, and please report any issues you come across.

**Comment by Brimcon** [comment]
Pretty good so far, exactly what I was hoping for it to do, just needs a little refinement. Though I believe I may have found a bug related to the Right Sidebar. When expanded on the "Player" side and you move/zoom the respective camera, it shifts a bit as if the side bar isn't there.
![image](https://user-images.githubusercontent.com/7198283/103331437-cc2c6a00-4a1a-11eb-9d3e-f09b6ff81be6.png)
This is what it looks like on the GM view.

But on the player it looks like this
![image](https://user-images.githubusercontent.com/7198283/103331464-f0884680-4a1a-11eb-8a9a-ceeca3ffd305.png)
I ssume with the "Blackened Sidebar" Option this won't be an issue.

**Comment by CDeenen** [comment]
Yep, was able to replicate it. Only with 'exclude sidebar' enabled, and by using the scale icon. The move icon seems to work fine.
I've just created one big issue with all the bugs I've found, and I've added yours to it:
https://github.com/CDeenen/LockView/issues/25

I won't be able to work on in until after new year, so you'll have to live with it for now :)

**Comment by CDeenen** [comment]
I believe this issue is solved in release v1.4.0. If you had the beta version installed, you probably need to uninstall it to get v1.4.0.
