### ISSUE TITLE
Suddenly not working with Always Centre[BUG]

### ISSUE THREAD

**Issue by dangerdaren** [CDeenen/LockView#49]
**Setup**
 - OS: Mac
 - Browser: Chrome
 - Module version: 1.4.11
 - Foundry version: 0.7.9
 - Gaming system & version: dnd5e
 - Any other modules enabled: yes

**Describe the bug**
I've been using this mod alongside Always Centred for a while now. I use this mod to keep the boundary around the scene so players can't see the canvas, and I use Always Centred to keep the party in view. This combination makes for a perfect in person setup, but just recently Lock View is making the Always Centred view bounce around a lot. Not sure what changed recently. Any chance of getting the two mods to work together again?

**Comment by CDeenen** [comment]
Did this start with the 1.4.11 update that just got released, or was this an issue before that?

**Comment by hugepedlar** [comment]
Can confirm this is still an issue, however not just with Always Centered. Lock View appears to cause very jerky screen movement whenever a token is dragged or keyboard-moved far enough to trigger a move of the canvas, whether via another module or core foundry behaviour. This even happens on maps with no specific Lock View settings configured.

**Comment by CDeenen** [comment]
I believe that I've fixed this issue, except for some situations, such as when you use the Lock View autoscale function and Always Centered autozoom at the same time, or 'bounding box' together with 'Lock Zoom' but without 'Lock Pan' (there's probably also other combinations). They will cause issues because you'll have both Lock View and Always Centered fighting for controlling the view of the user.
@hugepedlar I couldn't reproduce the issue when Always Centered wasn't enabled, but hopefully that is also fixed.

I'll be adding this to the next update, which I'll publish after I've done some testing. When that update is released at it didn't fix the issues, please let me know.
