### ISSUE TITLE
Activating a scene that is already loaded fails to hide some UI elements

### ISSUE THREAD

**Issue by tposney** [CDeenen/LockView#53]
If you switch between two scenes which are already loaded the left action buttons and scene navigation don't get hidden.
I think it is an issue with the scene activation being too "fast", i.e. less than 2 seconds, which is the timeout of newSceneLoad being set.

If I change line 34 of lockview.js to
```
Hooks.on("renderSceneNavigation", () => { if (true || newSceneLoad == false) setUI(sidebarCollapsed) });
```
the issue goes away. But, obviously I don't know anything about how that might impact other actions. The only down side seems to be that the initial collapse sidebar action does not fire.

**Comment by CDeenen** [comment]
I think I've found a proper fix for this, which will be added to the next update.

**Comment by tposney** [comment]
What was the fix?

**Comment by CDeenen** [comment]
Your suggestion was fine, I believe, so I implemented that (although I removed the `newSceneLoad == false` part, since that's not doing anything anymore. I'm not entirely sure why I added that part, so I'm hoping that I'm breaking something :p.

Additionally, I changed some code when the control buttons (or action buttons, as you called them) are rendered, to make sure that they are properly hidden or displayed. Lines 118 and 119 are now replaced with:
```
if (getEnable(game.userId) && canvas?.scene?.getFlag('LockView', 'collapseSidebar')) {
    if (newSceneLoad == true) ui.sidebar.collapse();
    setUI(ui.sidebar._collapsed);
}
```
The sidebar does collapse, which you reported stopped working. 
I'll be doing some more testing before I push the update, but it appears to be working fine.
