### ISSUE TITLE
[FEATURE] During 'Edit Viewbox' Mode, consider only zooming a viewbox when hovering over it.

### ISSUE THREAD

**Issue by MatthijsKok** [CDeenen/LockView#56]
**Is your feature request related to a problem? Please describe.**
A GM cannot zoom in or out it's own screen when 'Edit Viewbox' is enabled.
They now need to turn this switch on and off a lot.
If they could adjust their own viewbox while it is enabled, it reduces their workload.

**Describe the solution you'd like**
When 'Edit Viewbox' is enabled, only zoom a players viewbox when the GM's mouse is hovering over it.
It could also be added as an option if people prefer the current behaviour.

**Comment by CDeenen** [comment]
Sorry for not getting back at you earlier.
I agree that this would be a nice feature. I tried to implement it in the last update, but couldn't get it to work the way I wanted to. I really didn't want to delay the update any longer (since it added compatibility for Foundry v9), so I've pushed it back a bit. I can hopefully add it soon.

**Comment by CDeenen** [comment]
This has been added in the latest version (v1.5.3)
