### ISSUE TITLE
3d canvas compatibility [BUG]

### ISSUE THREAD

**Issue by ravingdragoon** [CDeenen/LockView#63]
**Setup**
 - OS: Windows 10
 - Browser: Google Chrome Version 96.0.4664.93 (Official Build) (64-bit)
 - Module version: 1.4.14
 - Foundry version: 0.8.9
 - Gaming system & version: DnD5e 1.5.5
 - Any other modules enabled: yes
 - 
**Describe the bug**
An unending string of warnings bogging down the dev console when logged in as a player.  I get about 5/second of these errors, and it never stops.

**Console Log**
```
libWrapper: Potential conflict detected between module Lock    View and module 3D Canvas.
  Detected non-libWrapper wrapping of       
  'Canvas.prototype.animatePan' by module LockView. This       will potentially lead to conflicts.
    🎁console_ui    @    libWrapper-notifications.js:61
🎁conflict    @    libWrapper-notifications.js:84
🎁warn_classic_wrapper    @    libWrapper-wrapper.js:772
🎁set_nonproperty    @    libWrapper-wrapper.js:750
🎁Canvas.prototype.animatePan#setter    @    libWrapper-wrapper.js:347
setBlocks    @    blocks.js:83
applySettings    @    lockview.js:365
await in applySettings (async)        
(anonymous)    @    lockview.js:44
_call    @    VM1765:4
callAll    @    foundry.js:153
🎁LightingLayer.prototype.refresh#perfect-vision    @    lighting.js:914
🎁LightingLayer.prototype.refresh#0    @    libWrapper-wrapper.js:182
_update    @    foundry.js:36533
(anonymous)    @    foundry.js:36509
setTimeout (async)        
_update    @    foundry.js:36509
schedule    @    foundry.js:36435
_LightingLayer_animateSource    @    df-active-lights.js:5
🎁LightingLayer.prototype._animateSource#0    @    libWrapper-wrapper.js:182
t.emit    @    ticker.min.js:8
e.update    @    ticker.min.js:8
_tick    @    ticker.min.js:8
requestAnimationFrame (async)        
_tick    @    ticker.min.js:8
requestAnimationFrame (async)        
_tick    @    ticker.min.js:8
requestAnimationFrame (async)        
_tick    @    ticker.min.js:8
requestAnimationFrame (async)        
_tick    @    ticker.min.js:8
requestAnimationFrame (async)        
_tick    @    ticker.min.js:8
requestAnimationFrame (async)        
_tick    @    ticker.min.js:8
requestAnimationFrame (async)        
_tick    @    ticker.min.js:8
requestAnimationFrame (async)        
_tick    @    ticker.min.js:8
requestAnimationFrame (async)        
_tick    @    ticker.min.js:8
requestAnimationFrame (async)        
_tick    @    ticker.min.js:8
requestAnimationFrame (async)        
_tick    @    ticker.min.js:8
requestAnimationFrame (async)        
_tick    @    ticker.min.js:8
requestAnimationFrame (async)        
_tick    @    ticker.min.js:8
```

**Additional Information**
I have also reported this to @theripper93 in his discord channel.

**Comment by CDeenen** [comment]
Hey, thanks for the issue report.
It doesn't surprise me that there's incompatibilities with that module, considering what it does.
Assuming TheRipper is willing to give me access to 3D Canvas, I will take a look at this when I have the time, I can't promise a solution anytime soon, because there is a good chance that 3D Canvas is way out of my league to understand, making it difficult to find a solution.

**Comment by theripper93** [comment]
i'm not really doing anything - the problem seems to be that you are not using libwrapper to wrap the canvaspan, i just have a simple wrapper for it

`
async function animatePan(wrapped,...args){
        if(game.Levels3DPreview?._active && game.Levels3DPreview.CONFIG.autoPan){
            const x = args[0].x;
            const y = args[0].y;
            const token = canvas.tokens.placeables.find(t => t.center?.x == x && t.center?.y == y);
            if(token){
                game.Levels3DPreview.setCameraToControlled(token);
            }
        }
        return wrapped(...args);
    }
`

**Comment by CDeenen** [comment]
> i'm not really doing anything - the problem seems to be that you are not using libwrapper to wrap the canvaspan, i just have a simple wrapper for it
> 
> ```js
> async function animatePan(wrapped,...args){
>         if(game.Levels3DPreview?._active && game.Levels3DPreview.CONFIG.autoPan){
>             const x = args[0].x;
>             const y = args[0].y;
>             const token = canvas.tokens.placeables.find(t => t.center?.x == x && t.center?.y == y);
>             if(token){
>                 game.Levels3DPreview.setCameraToControlled(token);
>             }
>         }
>         return wrapped(...args);
>     }
> ```
Thanks for your input.
I figured that was part of the problem. I tried implementing libwrapper but ran into some issues. I've been meaning to do that, but it has just gotten pushed further back. 
However, I'm not really in a position to check it right now, but if I remember correctly, the way I implemented it might not even interfere with yours. Whenever Lock View overrides canvaspan to lock the pan, it stores whatever is currently the canvaspan prototype (which would be the one from 3D Canvas), and when the pan is unlocked it reverts it back to the stored prototype. There might be some cases where this doesn't work out, I'll have to take a proper look at it.

However, and maybe I'm wrong here, I assumed that @ravingdragoon was refering to the following lines repeating often:
```
requestAnimationFrame (async)        
_tick    @    ticker.min.js:8
```
This doesn't really sound like something caused by Lock View, but I could be wrong.

**Comment by theripper93** [comment]
The _tick is just the pixi animation loop, it will error every time something goes wrong in the render loop, 3d canvas also does not use pixi :P. The root of the error here seems setBlocks or ApplySettings - I don’t have 0.8.9 to test but I can see that there isn’t a single line from 3d canvas in that error log, @ravingdragoon did you check if this happens regardless of 3d canvas?

**Comment by ravingdragoon** [comment]
Ugh, wrong version of 3d Canvas was installed due to a failed attempt to upgrade to V9. I didn't back up far enough in the versioning. So sorry!
