### ISSUE TITLE
[BUG] Error message always displayed in console when clickin 'Save' in Scene Config menu

### ISSUE THREAD

**Issue by jocolamarco** [CDeenen/LockView#74]
**Setup**
 - OS: [e.g. windows] Windows
 - Browser: [e.g. chrome, safari, Foundry app] Chrome
 - Module version: [e.g. 1.2.5] 1.5.2
 - Foundry version: [e.g. 0.8.6] 9.255
 - Gaming system & version: [e.g. dnd5e 1.3.3] pf2e 3.7.2.10819
 - Any other modules enabled: [yes/no] yes

**Describe the bug**
Error message always displayed in console when clickin 'Save' in Scene Config menu

**Screenshots**
![image](https://user-images.githubusercontent.com/45291719/160625045-a3569750-b651-409e-b903-114dab04d9dd.png)

![image](https://user-images.githubusercontent.com/45291719/160625158-8c1e5935-fdb2-4d48-99c5-32d8f514796f.png)

**Console Log**
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'tools')
[Detected 1 package: LockView]
    at closeSceneConfig (sceneConfig.js:261:75)
```

**Additional context**
n/a

**Comment by CDeenen** [comment]
Sorry for the late response. 
This error probably occurs because you have 'Hide Control Button' enabled. After saving the scene config, it tries to edit the control buttons so they display the current settings (e.g. zoom lock enabled or disabled). With 'Hide Control Button' enabled, these control buttons do not exist, so it throws an error. I forgot to add a check before it tries to do that, but this shouldn't cause any issues.
If you do not have 'Hide Control Button' enabled, and you're still getting this error, please let me know.

**Comment by CDeenen** [comment]
I will close this since there's no response
