### ISSUE TITLE
[FEATURE] Option to lock players movement on a Locked View (i.e. landing page)

### ISSUE THREAD

**Issue by apoapostolov** [CDeenen/LockView#92]
I have very WASD trigger-happy players who even on the landing page tend to move around just to fidget. I want to lock down movement on these pages because I use them for landing page with exact token position that I have to recover later after players all move around like headless chicken.

**Comment by CDeenen** [comment]
Thank you for your feature request.
Unfortunately this isn't something I'm looking at adding right now. However, I have some suggestions that might help:
-Pause the game when on the loading screen
-Use tiles with the token icons instead of tokens, this way the players cannot move them
-Use a module like Not Your Turn to block movement
